#!/usr/bin/env python3
"""Visualize Lane Robot labels on source images.

Default dataset layout:
    datasets/
    ├── images/
    │   ├── train/
    │   └── valid/
    ├── labels_corrected/
    │   ├── train/
    │   └── valid/
    └── labelview/             # generated by this script
        ├── train/
        └── valid/

Label line format:
    lane_id x1 y1 x2 y2 ... x56 y56

Coordinates are normally normalized to [0, 1]. x=-1 marks an invisible point.
For compatibility with the current LaneRobotDataset loader, x-grid indices are
also accepted when x > 1; use --x-grids to specify the grid count.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import cv2
import numpy as np

IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

LANE_NAMES = {
    0: "lane_follow",
    1: "lead_lane",
    2: "channel_left",
    3: "channel_right",
}

# OpenCV uses BGR colors.
LANE_COLORS = {
    0: (0, 0, 255),       # red
    1: (0, 255, 0),       # green
    2: (255, 128, 0),     # blue-orange
    3: (0, 255, 255),     # yellow
}


@dataclass
class ParsedLane:
    lane_id: int
    points: list[tuple[int, int] | None]


@dataclass
class ParseResult:
    lanes: list[ParsedLane]
    warnings: list[str]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Draw Lane Robot labels onto images and save them to labelview.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--dataset-root",
        type=Path,
        default=Path("/home/xhm/Desktop/ULTRALYTICS_LANE_ROBOT/datasets"),
        help="Dataset root containing images and labels_corrected.",
    )
    parser.add_argument(
        "--images",
        type=Path,
        default=None,
        help="Image directory. Defaults to DATASET_ROOT/images.",
    )
    parser.add_argument(
        "--labels",
        type=Path,
        default=None,
        help="Label directory. Defaults to DATASET_ROOT/labels_corrected.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output directory. Defaults to DATASET_ROOT/labelview.",
    )
    parser.add_argument(
        "--row-anchors",
        type=int,
        default=56,
        help="Expected number of (x, y) coordinate pairs in each lane row.",
    )
    parser.add_argument(
        "--x-grids",
        type=int,
        default=320,
        help="Number of x grids, used only when a label x value is greater than 1.",
    )
    parser.add_argument("--point-radius", type=int, default=3, help="Radius of each anchor point in pixels.")
    parser.add_argument("--line-width", type=int, default=2, help="Lane polyline width in pixels.")
    parser.add_argument(
        "--include-unlabeled",
        action="store_true",
        help="Also save images that have no matching label file.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite output images that already exist.",
    )
    return parser.parse_args()


def read_image(path: Path) -> np.ndarray | None:
    """Read an image using fromfile/imdecode so non-ASCII paths are supported."""
    try:
        data = np.fromfile(str(path), dtype=np.uint8)
        if data.size == 0:
            return None
        return cv2.imdecode(data, cv2.IMREAD_COLOR)
    except (OSError, ValueError):
        return None


def write_image(path: Path, image: np.ndarray) -> bool:
    """Write an image using imencode/tofile so non-ASCII paths are supported."""
    path.parent.mkdir(parents=True, exist_ok=True)
    suffix = path.suffix.lower()
    if suffix not in IMAGE_SUFFIXES:
        suffix = ".jpg"
        path = path.with_suffix(suffix)
    params: list[int] = []
    if suffix in {".jpg", ".jpeg"}:
        params = [cv2.IMWRITE_JPEG_QUALITY, 95]
    ok, encoded = cv2.imencode(suffix, image, params)
    if not ok:
        return False
    try:
        encoded.tofile(str(path))
        return True
    except OSError:
        return False


def scan_images(images_dir: Path) -> list[Path]:
    return sorted(
        path
        for path in images_dir.rglob("*")
        if path.is_file() and path.suffix.lower() in IMAGE_SUFFIXES
    )


def split_visible_segments(points: list[tuple[int, int] | None]) -> Iterable[list[tuple[int, int]]]:
    """Yield contiguous valid segments so x=-1 gaps are not connected."""
    segment: list[tuple[int, int]] = []
    for point in points:
        if point is None:
            if segment:
                yield segment
                segment = []
        else:
            segment.append(point)
    if segment:
        yield segment


def parse_label(
    label_path: Path,
    image_width: int,
    image_height: int,
    row_anchors: int,
    x_grids: int,
) -> ParseResult:
    warnings: list[str] = []
    lanes: list[ParsedLane] = []

    try:
        text = label_path.read_text(encoding="utf-8-sig")
    except UnicodeDecodeError:
        text = label_path.read_text(encoding="gb18030")
    except OSError as exc:
        return ParseResult([], [f"cannot read label: {exc}"])

    if not text.strip():
        return ParseResult([], ["empty label file"])

    seen_lane_ids: set[int] = set()

    for line_number, raw_line in enumerate(text.splitlines(), start=1):
        line = raw_line.strip()
        if not line:
            continue

        tokens = line.replace(",", " ").split()
        try:
            values = [float(token) for token in tokens]
        except ValueError:
            warnings.append(f"line {line_number}: contains a non-numeric token")
            continue

        if len(values) < 3:
            warnings.append(f"line {line_number}: fewer than one coordinate pair")
            continue

        lane_float = values[0]
        lane_id = int(lane_float)
        if lane_float != lane_id:
            warnings.append(f"line {line_number}: lane_id {lane_float} is not an integer")
            continue
        if lane_id not in LANE_NAMES:
            warnings.append(f"line {line_number}: lane_id {lane_id} is outside 0..3")
            continue
        if lane_id in seen_lane_ids:
            warnings.append(f"line {line_number}: duplicate lane_id {lane_id}")
        seen_lane_ids.add(lane_id)

        coordinate_count = len(values) - 1
        if coordinate_count % 2 != 0:
            warnings.append(f"line {line_number}: odd coordinate value count {coordinate_count}")

        pair_count = coordinate_count // 2
        if pair_count != row_anchors:
            warnings.append(
                f"line {line_number}: has {pair_count} pairs, expected {row_anchors}"
            )

        points: list[tuple[int, int] | None] = []
        for anchor_index in range(min(pair_count, row_anchors)):
            x = values[1 + 2 * anchor_index]
            y = values[2 + 2 * anchor_index]

            if x < 0:
                points.append(None)
                continue

            if not 0.0 <= y <= 1.0:
                warnings.append(
                    f"line {line_number}, anchor {anchor_index}: y={y:.6g} outside [0, 1]"
                )
                points.append(None)
                continue

            if 0.0 <= x <= 1.0:
                x_normalized = x
            elif 1.0 < x <= x_grids - 1:
                x_normalized = x / max(x_grids - 1, 1)
            else:
                warnings.append(
                    f"line {line_number}, anchor {anchor_index}: x={x:.6g} is invalid"
                )
                points.append(None)
                continue

            px = int(round(np.clip(x_normalized, 0.0, 1.0) * (image_width - 1)))
            py = int(round(np.clip(y, 0.0, 1.0) * (image_height - 1)))
            points.append((px, py))

        if pair_count < row_anchors:
            points.extend([None] * (row_anchors - pair_count))

        lanes.append(ParsedLane(lane_id=lane_id, points=points))

    return ParseResult(lanes, warnings)


def draw_translucent_box(
    image: np.ndarray,
    top_left: tuple[int, int],
    bottom_right: tuple[int, int],
    alpha: float = 0.55,
) -> None:
    overlay = image.copy()
    cv2.rectangle(overlay, top_left, bottom_right, (0, 0, 0), thickness=-1)
    cv2.addWeighted(overlay, alpha, image, 1.0 - alpha, 0.0, dst=image)


def draw_legend(image: np.ndarray, active_lane_ids: set[int], font_scale: float) -> None:
    if not active_lane_ids:
        return

    line_height = max(20, int(round(26 * font_scale / 0.6)))
    x0, y0 = 12, 12
    width = max(210, int(round(245 * font_scale / 0.6)))
    height = 12 + line_height * len(active_lane_ids)
    draw_translucent_box(image, (x0, y0), (x0 + width, y0 + height))

    for row, lane_id in enumerate(sorted(active_lane_ids)):
        y = y0 + 8 + line_height * row + int(line_height * 0.65)
        color = LANE_COLORS[lane_id]
        cv2.line(image, (x0 + 10, y - 5), (x0 + 38, y - 5), color, thickness=4)
        cv2.putText(
            image,
            f"{lane_id}: {LANE_NAMES[lane_id]}",
            (x0 + 48, y),
            cv2.FONT_HERSHEY_SIMPLEX,
            font_scale,
            (255, 255, 255),
            thickness=1,
            lineType=cv2.LINE_AA,
        )


def draw_status(image: np.ndarray, text: str, color: tuple[int, int, int]) -> None:
    font_scale = max(0.55, min(image.shape[0], image.shape[1]) / 900.0)
    thickness = max(1, int(round(font_scale * 2)))
    (text_width, text_height), baseline = cv2.getTextSize(
        text, cv2.FONT_HERSHEY_SIMPLEX, font_scale, thickness
    )
    x0, y0 = 12, image.shape[0] - text_height - baseline - 18
    draw_translucent_box(
        image,
        (x0, y0),
        (x0 + text_width + 18, image.shape[0] - 10),
    )
    cv2.putText(
        image,
        text,
        (x0 + 9, image.shape[0] - baseline - 14),
        cv2.FONT_HERSHEY_SIMPLEX,
        font_scale,
        color,
        thickness=thickness,
        lineType=cv2.LINE_AA,
    )


def visualize(
    image: np.ndarray,
    parsed: ParseResult,
    point_radius: int,
    line_width: int,
) -> np.ndarray:
    canvas = image.copy()
    h, w = canvas.shape[:2]
    font_scale = max(0.45, min(h, w) / 1100.0)
    active_lane_ids: set[int] = set()

    for lane in parsed.lanes:
        color = LANE_COLORS[lane.lane_id]
        valid_points = [point for point in lane.points if point is not None]
        if not valid_points:
            continue

        active_lane_ids.add(lane.lane_id)

        for segment in split_visible_segments(lane.points):
            if len(segment) >= 2:
                array = np.asarray(segment, dtype=np.int32).reshape(-1, 1, 2)
                cv2.polylines(
                    canvas,
                    [array],
                    isClosed=False,
                    color=color,
                    thickness=max(1, line_width),
                    lineType=cv2.LINE_AA,
                )

        for point in valid_points:
            cv2.circle(
                canvas,
                point,
                radius=max(1, point_radius),
                color=color,
                thickness=-1,
                lineType=cv2.LINE_AA,
            )

        # Label each lane near its uppermost visible point.
        label_point = min(valid_points, key=lambda point: point[1])
        label_x = int(np.clip(label_point[0] + 7, 0, max(w - 1, 0)))
        label_y = int(np.clip(label_point[1] - 7, 14, max(h - 1, 14)))
        label_text = f"{lane.lane_id}:{LANE_NAMES[lane.lane_id]}"
        cv2.putText(
            canvas,
            label_text,
            (label_x, label_y),
            cv2.FONT_HERSHEY_SIMPLEX,
            font_scale,
            color,
            thickness=max(1, line_width),
            lineType=cv2.LINE_AA,
        )

    draw_legend(canvas, active_lane_ids, font_scale=max(0.48, font_scale))

    if not parsed.lanes:
        draw_status(canvas, "EMPTY LABEL", (0, 165, 255))
    elif not active_lane_ids:
        draw_status(canvas, "NO VISIBLE LANE POINTS", (0, 165, 255))

    if parsed.warnings:
        draw_status(canvas, f"LABEL WARNINGS: {len(parsed.warnings)}", (0, 165, 255))

    return canvas


def main() -> int:
    args = parse_args()

    if args.row_anchors <= 0:
        print("ERROR: --row-anchors must be greater than 0", file=sys.stderr)
        return 2
    if args.x_grids <= 1:
        print("ERROR: --x-grids must be greater than 1", file=sys.stderr)
        return 2

    dataset_root = args.dataset_root.expanduser().resolve()
    images_dir = (args.images or dataset_root / "images").expanduser().resolve()
    labels_dir = (args.labels or dataset_root / "labels_corrected").expanduser().resolve()
    output_dir = (args.output or dataset_root / "labelview").expanduser().resolve()

    if not images_dir.is_dir():
        print(f"ERROR: image directory does not exist: {images_dir}", file=sys.stderr)
        return 2
    if not labels_dir.is_dir():
        print(f"ERROR: label directory does not exist: {labels_dir}", file=sys.stderr)
        return 2

    images = scan_images(images_dir)
    if not images:
        print(f"ERROR: no images found under: {images_dir}", file=sys.stderr)
        return 2

    print(f"Images : {images_dir}")
    print(f"Labels : {labels_dir}")
    print(f"Output : {output_dir}")
    print(f"Found  : {len(images)} image(s)\n")

    counters: Counter[str] = Counter()
    lane_counts: Counter[int] = Counter()

    for index, image_path in enumerate(images, start=1):
        relative_path = image_path.relative_to(images_dir)
        label_path = labels_dir / relative_path.with_suffix(".txt")
        output_path = output_dir / relative_path

        if output_path.exists() and not args.overwrite:
            counters["skipped_existing"] += 1
            continue

        if not label_path.exists() and not args.include_unlabeled:
            counters["skipped_unlabeled"] += 1
            continue

        image = read_image(image_path)
        if image is None:
            counters["broken_images"] += 1
            print(f"[WARN] Cannot read image: {image_path}")
            continue

        if label_path.exists():
            parsed = parse_label(
                label_path=label_path,
                image_width=image.shape[1],
                image_height=image.shape[0],
                row_anchors=args.row_anchors,
                x_grids=args.x_grids,
            )
            counters["with_label"] += 1
            counters["label_warnings"] += len(parsed.warnings)
            for lane in parsed.lanes:
                lane_counts[lane.lane_id] += 1

            if parsed.warnings:
                print(f"[WARN] {label_path}")
                for warning in parsed.warnings:
                    print(f"       - {warning}")
        else:
            parsed = ParseResult([], ["missing label file"])
            counters["without_label"] += 1

        rendered = visualize(
            image=image,
            parsed=parsed,
            point_radius=args.point_radius,
            line_width=args.line_width,
        )

        if not write_image(output_path, rendered):
            counters["write_failures"] += 1
            print(f"[WARN] Cannot write output: {output_path}")
            continue

        counters["saved"] += 1
        if index % 100 == 0 or index == len(images):
            print(f"[{index:>6}/{len(images)}] saved={counters['saved']}")

    print("\nDone.")
    print(f"Saved images        : {counters['saved']}")
    print(f"Skipped unlabeled   : {counters['skipped_unlabeled']}")
    print(f"Skipped existing    : {counters['skipped_existing']}")
    print(f"Broken images       : {counters['broken_images']}")
    print(f"Write failures      : {counters['write_failures']}")
    print(f"Total label warnings: {counters['label_warnings']}")
    print("Lane rows visualized:")
    for lane_id in sorted(LANE_NAMES):
        print(f"  {lane_id} {LANE_NAMES[lane_id]:<14}: {lane_counts[lane_id]}")
    print(f"\nResults are in: {output_dir}")

    return 1 if counters["broken_images"] or counters["write_failures"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
